### ISSUE TITLE
Make available on bower

### ISSUE THREAD

**Issue by codeconsole** [ChadKillingsworth/geolocation-marker#1]
Would be great to be able to use this via bower:

bower install geolocation-marker

**Comment by ChadKillingsworth** [comment]
The thing is, there are so many package registries it's hard to keep up. And I believe that sometime soon bower may be able to [natively install from the NPM registry](https://github.com/bower/bower/issues/1520). At that point, I'll happily add any meta data to the package.json file so it is available via bower.
