### ISSUE TITLE
tracking marker disappeared

### ISSUE THREAD

**Issue by fdu-axiometrics** [ChadKillingsworth/geolocation-marker#11]
Thank you for this awesome library!!

I was able to use this in our mobile development.

However, we found an issue while using in driving. The marker disappeared after some time.

I have created a plunker to replicate the issue. Please see here. (wait for a few updates, then the blue dot disappeared)
http://plnkr.co/edit/OguwHiNiWQGHpSdPMQGy?p=preview

Thank you!!

**Comment by ChadKillingsworth** [comment]
Interesting. Changing the map zoom brings the marker back. I'm guessing this is a bug in the map api itself. I'll have to test this with a standard marker though to be sure.

**Comment by ChadKillingsworth** [comment]
This is indeed a bug with the maps api. I've reported it here: https://code.google.com/p/gmaps-api-issues/issues/detail?id=8985

**Comment by fdu-axiometrics** [comment]
Thanks! Do you think there is a way to solve this by redrawing the map somehow? This is very important for us. 
Thanks for the help!

**Comment by fdu-axiometrics** [comment]
I just changed "optimized = true." It seems it is working now.
I'm not sure if this will influence anything?
Thanks!

**Comment by ChadKillingsworth** [comment]
Optimized true forces canvas markers rather than dom markers. It should be just fine to set it that way.

**Comment by gaharrington** [comment]
I have added optimized: true, but I am still having this issue will geolocation-marker v2.0.4. 

Is this still considered a google maps bug?

I am using this in an Ionic app. Here is the relevant code:
`vm.map = new google.maps.Map(document.getElementById("exploremap"), {
            center: new google.maps.LatLng(Geo.currentPosition.lat, Geo.currentPosition.lng),
            zoom: 12,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            disableDefaultUI: true
          });
          var GeoMarker = new GeolocationMarker(
              vm.map,
              {optimized: true}
              );`

**Comment by gaharrington** [comment]
In your docs, I do see the event: geolocation_error

How do a capture these?

**Comment by ChadKillingsworth** [comment]
Closed by 7f93e29916a444b9dd3fa0ed0848355469449e53
