### ISSUE TITLE
Unable to click other markers on map inside the location circle.

### ISSUE THREAD

**Issue by ansonl** [ChadKillingsworth/geolocation-marker#12]
When other markers on the map are inside the geolocation circle, they are 'unclickable'. 
[Screenshot of this](http://i.imgur.com/KVSQz8u.png)
 I am also unable to drag the map if dragging from inside the circle. 
I see that the circle marker has a `zIndex`of 2 and the circle outline is `zIndex`of 1 and have tried setting my markers to a higher `zIndex`to no avail. 

Is there an option to allow clicking of markers inside the geolocation circle?

**Comment by ChadKillingsworth** [comment]
zIndex on google maps api only affects relationship to similar objects. For instance, zIndex on the circle class only affects the relationship to other polygons - not to markers.

I'll have to create a repo case and play around with this to see the effect. May be a maps api issue which in that case there will be little that can be done.

**Comment by ChadKillingsworth** [comment]
I changed the marker defaults to use optimized markers again. Is this still an issue?

**Comment by ChadKillingsworth** [comment]
Closing until I hear this is still an issue.
