### ISSUE TITLE
set zoom default

### ISSUE THREAD

**Issue by abedputra** [ChadKillingsworth/geolocation-marker#13]
How to set zoom default?

**Comment by Saint-Cyr** [comment]
How to set the default value of the Zoom of the map ?? Same issue...

**Comment by ChadKillingsworth** [comment]
This is a question best asked on stackoverflow.com. The geolocation-marker doesn't set or change the map zoom level. My example page does contain code to center the map and zoom to the accuracy of the position, but that code isn't even part of this library.

**Comment by abedputra** [comment]
I edit this code for zoom
`        google.maps.event.addListenerOnce(GeoMarker, 'position_changed', function() {
          map.setCenter(this.getPosition());
          map.fitBounds(this.getBounds()); // I delete this code for zoom
        });`
May help for your problem.

**Comment by Saint-Cyr** [comment]
Thank you abedputra ! In fact normally as ChadKillingsworth said, we should not touch the library when we want to configure the zoom of google map but please  ChadKillingsworth notice that it does not work till we edit like abedputra show .... Thank to all of you.
