### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by ilentt** [ChadKillingsworth/geolocation-marker#14]
Your API work so well when point to API on your host, but when I upload into my host it is not work. Browser prompt the error message `geolocation-marker.js:273 Uncaught SyntaxError: Unexpected token export` at the line `export default GeolocationMarker;`

Please review this bug at
https://ilentt-developer-edition.ap1.force.com/kz_trackinggps_page

I look forward your reply.

Thank you.

**Comment by ChadKillingsworth** [comment]
The source files are meant to be built with other files. For simple usage, see the [Direct download](https://github.com/ChadKillingsworth/geolocation-marker#direct-download) section of the readme.

**Comment by ilentt** [comment]
Thank you for your reply.

In my case, I have used newest version API following your guideline in readme. When I ran on local just only one API(`geolocation-marker.js`) with one HTML and did not link with any other file in package `geolocation-marker-2.0.4.zip` you're API work perfectly. However when I upload into salesforce it did not work, it just work if I point direct into API on your host.

I have double check link on salesforce, everything is ok. I don't know why did not work. Do you have any suggestion in this case./

Thank you.

**Comment by ChadKillingsworth** [comment]
You are using the source files. I can tell because it has the keyword `export` in it which browsers don't recognize. You need the built file: https://github.com/ChadKillingsworth/geolocation-marker/releases/download/v2.0.4/geolocation-marker.js
