### ISSUE TITLE
Trying to use with jQuery.getScript()

### ISSUE THREAD

**Issue by cheesegrits** [ChadKillingsworth/geolocation-marker#15]
Hi,

I'm coding in a shared sandbox (the Joomla CMS), where for various reasons I have to load the maps API dynamically.  I'm trying to then load geolocation-marker from within my maps callback:

```javascript
				var self = this;
				jQuery.getScript(src)
					.done(function (data, textStatus, jqxhr) {
						self.geoMarker = new GeolocationMarker(self.map);
					})
					.fail(function( jqxhr, settings, exception ) {
						console.log('dammit');
					}
				);
```

... but no matter what I try

Uncaught ReferenceError: GeolocationMarker is not defined(…)

I don't think it's a race condition with the script not having executed, as I've tried all kinds of ways.

Any ideas?

**Comment by ChadKillingsworth** [comment]
Do you have a module loader? Does either the `define.amd` or `module.exports` symbols exist?

**Comment by cheesegrits** [comment]
Hmmm.  Well, I use requirejs for most of my loading, but for the maps API I can't do that.  However, if I stick a breakpoint inside the done() closure, define.amd is an object, {jQuery: true}

**Comment by cheesegrits** [comment]
w00t!

Yes, if I replace ...

```javascript
"function"===typeof this.define&&this.define.amd?this.define([],m):"object"===typeof this.exports?this.module.exports=m():this.GeolocationMarker=m();
```

... with just ...

```javascript
this.GeolocationMarker=m();
```

... it works.  I'm not well versed in module loaders, but I guess because I have requirejs loaded, define.amd exists, so this module thinks it's being loaded by requirejs, which would sprinkle some magic module loading dust to make it work.

I don't know if this can be worked around, but don't lose sleep over it.  My setup is pretty corner case, and I'm happy enough just modifying my copy.

Thank you VERY much for the fast response and nudging me in the right direction.

**Comment by ChadKillingsworth** [comment]
So rather than use jQuery, can't you use requirejs in your callback?

**Comment by cheesegrits** [comment]
I did try, but ran into other issues.  Which may well have been down to my rather limited grasp of how all this stuff works.  But I shall give it another go, now I know that's definitely the issue.

Once again, thanks for your prompt responses.

**Comment by cheesegrits** [comment]
OK, duh, I'd left out the module name arg in the callback function when trying to do it with requirejs.  This works:

```javascript
				var self = this;
				requirejs(['lib/geolocation-marker/geolocation-marker-min'], function(GeolocationMarker) {
					self.geoMarker = new GeolocationMarker(self.map);
				});
```

**Comment by ChadKillingsworth** [comment]
Glad it worked.
