### ISSUE TITLE
Keep circle visible regardless of zoom size

### ISSUE THREAD

**Issue by louman** [ChadKillingsworth/geolocation-marker#18]
Hi, is it possible to keep the circle around the marker visible regardless of the zoom size?

**Comment by ChadKillingsworth** [comment]
It shouldn't be hiding itself at different zoom levels. The only thing that prevents the accuracy circle is if you use the `setMinimumAccuracy` method. I frequently use that as otherwise the accuracy circle is half the size of Texas - which isn't really useful. But that shouldn't be a default either.

**Comment by louman** [comment]
It's not hiding per say. 

I think it's because the area of the circle doesn't change as you zoom out so the further away you go, the smaller it gets to a point that it disappears. I guess it's by design?

**Comment by ChadKillingsworth** [comment]
Correct - accuracy is a fixed number. As you zoom in, you can zoom closer than the accuracy.

**Comment by louman** [comment]
Is it possible to keep a min size just like googlemaps.com does? So at least something stays visible?

**Comment by ChadKillingsworth** [comment]
You could prevent zooming in, or you could use `setMinimumAccurracy` to hide the circle properly below certain zoom levels. Then you could add your own indicator.

But there's nothing automatic, no. You are realistically lying to the user when you do that.

**Comment by louman** [comment]
yeah I agree with you. Would you consider a PR for improving the visual of the marker?

**Comment by ChadKillingsworth** [comment]
Sure would.

**Comment by louman** [comment]
https://github.com/ChadKillingsworth/geolocation-marker/pull/19
