### ISSUE TITLE
Accessing images via http

### ISSUE THREAD

**Issue by janoskk** [ChadKillingsworth/geolocation-marker#2]
Currently, the location marker image is accessed via http instead of https that causes warnings at some browsers, especially when the website is visited via https. Please consider changing the url in the following code at src/geolocationmarker.js:
```
  var markerOpts = {
    'clickable': false,
    'cursor': 'pointer',
    'draggable': false,
    'flat': true,
    'icon': {
        'url': 'http://chadkillingsworth.github.io/geolocation-marker/images/gpsloc.png',
        'size': new google.maps.Size(34, 34),
        'scaledSize': new google.maps.Size(17, 17),
        'origin': new google.maps.Point(0, 0),
        'anchor': new google.maps.Point(8, 8)
    },
```

**Comment by ChadKillingsworth** [comment]
Fixed by 3b1918ccaa807758d13eb347709b8e30548b8b93

I'll publish to npm later this week.
