### ISSUE TITLE
What does SetMap method do

### ISSUE THREAD

**Issue by MSIH** [ChadKillingsworth/geolocation-marker#20]
In the example, you use  `GeoMarker.setMap(map);` but no in the instruction on the readme. What does this method do?

In the example, you also set a listener. What does this method do?
```
   google.maps.event.addListenerOnce(GeoMarker, 'position_changed', function() {
          map.setCenter(this.getPosition());
          map.fitBounds(this.getBounds());
        });
```

**Comment by ChadKillingsworth** [comment]
That makes the map center and follow the marker as it moves.
