### ISSUE TITLE
Delay location permission

### ISSUE THREAD

**Issue by whitecat** [ChadKillingsworth/geolocation-marker#21]
How do I delay the request for location permission until the button is pushed?

**Comment by tremby** [comment]
@whitecat, what symptom are you seeing? I'm seeing a delay between the user allowing access and the location becoming available, and wondering if it's related.

**Comment by ChadKillingsworth** [comment]
Permission is requested when the marker is first added to the map. Don't add the marker to the map until you are ready to prompt for permission.

**Comment by tremby** [comment]
That's what I'm doing, not sure about the OP.
