### ISSUE TITLE
How to clearWatch()

### ISSUE THREAD

**Issue by M-Husein** [ChadKillingsworth/geolocation-marker#23]
Hi, ChadKillingsworth

Thanks for your nice work.
I want to stop  **geolocation.watchPosition()** method with  **geolocation.clearWatch()**, 
but I can't  find this method in your object, can you add **geolocation.clearWatch()** in your library object?

Please add this.

Thanks ;)

**Comment by ChadKillingsworth** [comment]
Remove the marker from the map. That clears the watch.

```js
geolocationMarker.setMap(null);
```

**Comment by M-Husein** [comment]
Thanks for fast respon :)

I will try this, 
Just for make sure, this is can stop watchPosition() or just remove the marker?

**Comment by ChadKillingsworth** [comment]
The library manages the location watches on its own. Just remove the marker from the map and the watch will automatically be cleared.
