### ISSUE TITLE
I followed the instruction but contains an error

### ISSUE THREAD

**Issue by sabarinathen** [ChadKillingsworth/geolocation-marker#24]
`Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_4_geolocation_marker__.GeolocationMarker is not a constructor TypeError: __WEBPACK_IMPORTED_MODULE_4_geolocation_marker__.GeolocationMarker is not a constructor at http://localhost:8100/build/main.js:281:29 at t.invoke (http://localhost:8100/build/polyfills.js:3:9283) at Object.onInvoke (http://localhost:8100/build/vendor.js:4508:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:9223) at r.run (http://localhost:8100/build/polyfills.js:3:4452) at http://localhost:8100/build/polyfills.js:3:14076 at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967) at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37) at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888) at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
`
**Here is my step:**

step1: **npm install geolocation-marker --save**

step 2: **import the statement import { GeolocationMarker } from ‘geolocation-marker’;**

step 3: finally i added the geolocation marker in the map loaded

```
 loadMap() {
   
    this.geolocation.getCurrentPosition().then((position) => {
          console.log("Curr",position);
      let latLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude); 
   
   console.log("cuur",position.coords.latitude);
      let mapOptions = {
        center: latLng,
        zoom: 15,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      }
       this.map = new google.maps.Map(this.mapElement.nativeElement, mapOptions);
       
      console.log("Well", latLng);
      var GeoMarker = new GeolocationMarker(this.map);

    }, (success) => {
      console.log(success);
    });

  }
```
The above error i was faced…Any help??

**Comment by ChadKillingsworth** [comment]
You are using ES Modules with webpack. Nice. 

I think your import statement is wrong which is the problem. 

```js
import GeolocationMarker from 'geolocation-marker' ;
```

It is the default export so you don't need destructuring.

**Comment by sabarinathen** [comment]
so how can i give the import statement without importing it contains an error in Geolocation marker?

**Comment by ChadKillingsworth** [comment]
```js
// after google maps api has loaded 
import('geolocation-marker') 
  .then(marker => {
    const GeolocationMarker = marker.default;
    // use marker
 }) ;
```

**Comment by RaschidJFR** [comment]
I've just opened an [issue](https://github.com/ChadKillingsworth/geolocation-marker/issues/26) that might be related to this. I'm doing `import GeolocationMarker from 'geolocation-marker' ;` but it returns an empty object `{}` so then I get the error you're describing.
