### ISSUE TITLE
geomarker.html:34 Uncaught ReferenceError: GeolocationMarker is not defined 

### ISSUE THREAD

**Issue by MSIH** [ChadKillingsworth/geolocation-marker#25]
When I used the js file from the github repo I am getting this error.

<script src="https://raw.githubusercontent.com/ChadKillingsworth/geolocation-marker/master/src/geolocation-marker.js"></script>

geomarker.html:34 Uncaught ReferenceError: GeolocationMarker is not defined at initialize 

But if i used the min version, thenit does work.
https://chadkillingsworth.github.io/geolocation-marker/geolocation-marker.js

Please advise

**Comment by ChadKillingsworth** [comment]
The library uses ES modules which won't run in a browser. You need to use the released version.

**Comment by MSIH** [comment]
I do not see a release folder in the repo. Where do you get it? Thanks

**Comment by MSIH** [comment]
i found it 

https://github.com/ChadKillingsworth/geolocation-marker/releases
