### ISSUE TITLE
Can't get your example.html to work.

### ISSUE THREAD

**Issue by fatfantasma** [ChadKillingsworth/geolocation-marker#4]
Hey Chad,

I am out of my depth on this ESM 6 stuff.  I never heard of it.  I downloaded your latest version and can't get your example.html to work by clicking on it.  I just get the same close up zoom to Australia.  What is the exact file that I am supposed to include in my project to get this to work?  I also included another screen shot that gives an error in Pycharm of your code.  Sorry for being a JS newbie :)
![capture](https://cloud.githubusercontent.com/assets/10077915/10908596/b840e0f8-81e7-11e5-82df-c6bc78827725.PNG)

**Comment by ChadKillingsworth** [comment]
All you need is this file: https://github.com/ChadKillingsworth/geolocation-marker/releases/download/v2.0.2/geolocation-marker.js

That is the pre-built source as ES5 syntax so it works in all supported browsers (back to IE9).
