### ISSUE TITLE
GeoLocation-Marker not defined when using async defer with maps api

### ISSUE THREAD

**Issue by MSIH** [ChadKillingsworth/geolocation-marker#9]
When I include "async defer" in the script line:

    <script src="https://maps.googleapis.com/maps/api/js?&callback=initMap"
            async defer></script>

I get an error: GeoLocation-Marker not defined 

Any ideas why this is happening?

**Comment by ChadKillingsworth** [comment]
Your questions are best asked on stackoverflow.com as they are not bugs in this library.
